/** V78 map construction extracted from Game. */
import DATA from '../data/imperial-data.js';

const D = DATA;

export function buildMaps() {const maps={};const names=Object.keys(D.species).filter(n=>!D.legends.includes(n));const tiers=[5,16,24,31,38,45,51,55];const evolutionMin={};Object.values(D.species).forEach(d=>{if(d.evo)evolutionMin[d.evo.to]=d.evo.level;});const pools=Array.from({length:8},()=>[]);names.forEach((n,j)=>pools[j%8].push(n));pools[0]=[...new Set(['Bidoof','Starly','Shinx','Erbello','Weedle','Scarab',...pools[0]])];
 const make=(id,name,theme='grass',kind='route',level=5)=>{const m={id,name,theme,kind,level,w:26,h:18,grid:[],objects:[],pool:[],description:''};for(let y=0;y<18;y++){m.grid[y]=[];for(let x=0;x<26;x++){const border=x===0||y===0||x===25||y===17;let t=border?'wall':'grass';if(kind==='route'){if((x*7+y*11)%17<3&&x!==13&&y!==9)t='tree';if(x>=18&&x<=20&&y>1&&y<16)t='water';if(y===9||x===13)t='path';if(y===9&&x>=18&&x<=20)t='bridge';if(x>=3&&x<=10&&y>=4&&y<=7)t='tall';}else if(['gym','interior','dungeon','league'].includes(kind)){t=border?'wall':'floor';if(x===13||y===9)t='carpet';if(kind==='dungeon'&&(x*3+y*7)%19<3&&x!==13&&y!==9)t='rock';}else{if(x===13||y===9||y===13)t='path';if((x+y*3)%31===0&&x!==13&&y!==9&&y!==13)t='flower';}m.grid[y][x]=t;}}maps[id]=m;return m;};
 const obj=(m,o)=>{m.objects.push(o);if(o.kind==='door'){for(let dy=-2;dy<=-1;dy++)for(let dx=-2;dx<=2;dx++)if(m.grid[o.y+dy]?.[o.x+dx])m.grid[o.y+dy][o.x+dx]='wall';}if(o.kind!=='decor')m.grid[o.y][o.x]=m.kind==='route'?'path':m.kind==='town'?'path':'floor';return o;};
 const exit=(m,x,y,to,tx=13,ty=14,gate=null)=>obj(m,{kind:'exit',x,y,to,tx,ty,gate,name:'Passaggio'});
 const sign=(m,x,y,name,text)=>obj(m,{kind:'sign',x,y,name,text});
 const trainer=(m,x,y,id,name,team,extra={})=>obj(m,{kind:'trainer',x,y,id,name,team,...extra});
 const home=make('home','Borgofoglia','grass','town');sign(home,9,10,'Professor Vannaccius','Le otto medaglie apriranno la Via Imperiale. Torna nei centri per curare HP e PP. Esplora i santuari laterali: le reliquie raccontano una storia diversa da quella ufficiale.');sign(home,16,13,'Mira, la cartografa','Frecce o WASD per camminare. Spazio o E per interagire. Nell’erba alta trovi incontri. Premi M per la mappa.');exit(home,13,1,'r0');
 for(let i=0;i<8;i++){const g=D.gyms[i],r=make('r'+i,D.routes[i],['grass','forest','stone','sky','fire','ghost','dragon','grass'][i],'route',tiers[i]);r.pool=pools[i].filter(n=>(evolutionMin[n]||1)<=tiers[i]+3);if(!r.pool.length)r.pool=['Bidoof'];exit(r,13,16,i?'c'+(i-1):'home',13,2);exit(r,13,1,'c'+i,13,14,i===1?'event-rival':i===3?'event-archive':i===6?'event-crown':null);trainer(r,11,9,'route-'+i,['Ada','Minatore Enzo','Studiosa Livia','Custode Neri','Fabbro Orin','Pellegrina Lea','Cavaliere Ruan','Botanica Iris'][i],[[pools[i][0],tiers[i]],[pools[i][1],tiers[i]+1]]);obj(r,{kind:'item',x:6,y:6,id:'route-item-'+i,name:'Scorta da viaggio',item:i>3?'ultra':'potion',qty:3});
 if(i===1)trainer(r,13,3,'event-rival','Impero Ottomano · pattuglia',[['Vargan',16],['Zubat',16]],{double:true,story:'Il tuo rivale Elio si schiera al tuo fianco. Due reclute stanno sottraendo una tavoletta: affrontatele insieme!',after:'Elio: questa tavoletta parla di una guerra senza vincitori. Ci ritroveremo negli archivi di Astravia.'});
 if(i===3)trainer(r,13,3,'event-archive','Capitana Selma',[['Murkrow',29],['Ferryn',30],['Morvik',31]],{story:'Selma: gli archivi devono restare sigillati. Senza una storia comune, nessuno metterà in dubbio la nostra conquista.',after:'L’archivista ti consegna la cronaca autentica: il regno fu diviso per fermare una guerra, non per obbedire a un nuovo imperatore.'});
 if(i===6)trainer(r,13,3,'event-crown','Gran Visir Azhar',[['Houndoom',53],['Armoryn',54],['Vargor',54],['Dravurion',55]],{story:'Azhar vuole imporre la Corona Imperiale a Blanchivus. Il santuario rifiuta il suo ordine. È il momento di fermare l’esercito.',after:'La Corona si spezza e il sigillo si apre. Azhar si ritira: il guardiano ha scelto la libertà. Draconia può finalmente raccontare la verità.'});
 const c=make('c'+i,g.city,r.theme,'town',g.level);c.description=['Un’abbazia fra campi e tessitori.','Rotaie, pietra e officine sotto la montagna.','La città degli archivi e delle stelle.','Torri bianche sulle correnti del mare.','Una fortezza che vive attorno alla caldera.','Le campane custodiscono la memoria del regno.','La promessa dei draghi incisa nella pietra.','Giardini, canali e serre nella valle.'][i];exit(c,13,16,'r'+i,13,2);exit(c,13,1,i===7?'victory':'r'+(i+1),13,14,'badge-'+(i+1));obj(c,{kind:'door',x:13,y:5,to:'g'+i,tx:13,ty:14,name:'Palestra · '+g.leader});sign(c,18,10,'Abitante',c.description+' Il Capopalestra custodisce la Medaglia '+g.badge+'.');exit(c,24,9,'d'+i,2,9);const d=make('d'+i,D.dungeons[i],r.theme,'dungeon',tiers[i]+3);d.pool=pools[i].filter(n=>(evolutionMin[n]||1)<=tiers[i]+6);exit(d,1,9,'c'+i,23,9);obj(d,{kind:'relic',x:13,y:3,id:'relic-'+i,name:'Frammento della memoria',text:['Il primo regno nacque da un patto fra città libere.','Il ferro della miniera costruì ponti prima delle armi.','Le cronache furono riscritte dopo la Prima Guerra.','Le isole si separarono, ma le rotte rimasero aperte.','Le forge alimentarono la guerra. Ora possono ricostruire.','Ogni nome ricordato restituisce dignità a chi è caduto.','Blanchivus riconosce la promessa, non il potere della corona.','Il regno vive di ciò che viene coltivato insieme.'][i]});obj(d,{kind:'item',x:21,y:13,id:'material-'+i,name:'Minerale antico',item:'material',qty:2});trainer(d,12,8,'dungeon-'+i,'Custode della memoria',[[pools[i][2],tiers[i]+3]]);
 const gym=make('g'+i,'Palestra di '+g.city,r.theme,'gym',g.level);exit(gym,13,16,'c'+i,13,6);sign(gym,13,12,'Iscrizione','Attiva i tre sigilli in questo ordine: '+g.puzzle.join(' → ')+'. Una scelta errata spegne tutti i sigilli.');[0,1,2].forEach(k=>obj(gym,{kind:'switch',x:[6,13,20][k],y:8,index:[1,2,0][k],gym:i,name:g.puzzle[[1,2,0][k]]}));trainer(gym,8,11,'gym-trainer-'+i,'Apprendista di '+g.leader,[[g.team[0][0],g.level-2]]);obj(gym,{kind:'leader',x:13,y:3,gym:i,name:g.leader});
 }
 for(const m of Object.values(maps).filter(m=>m.kind==='town')){for(const [kind,x] of [['center',5],['shop',21]]){obj(m,{kind:'door',x,y:6,to:m.id+'-'+kind,tx:13,ty:14,name:kind==='center'?'Centro di cura':'Emporio'});const room=make(m.id+'-'+kind,kind==='center'?'Centro di cura · '+m.name:'Emporio · '+m.name,m.theme,'interior');exit(room,13,16,m.id,x,7);obj(room,{kind,x:13,y:5,name:kind==='center'?'Infermiera':'Mercante',home:m.id});if(kind==='center')obj(room,{kind:'box',x:20,y:5,name:'Terminale Box'});} }
 const v=make('victory','Via Imperiale','stone','route',61);v.pool=['Dravurion','Armoryn','Aquilord','Brumagnus','Vargor'];exit(v,13,16,'c7',13,2);exit(v,13,1,'league',13,14,'badges');trainer(v,13,4,'final-rival','Elio · ultima sfida',[['Ramgarth',60],['Veyron',60],['Elarion',60],['Astrelios',61]],{after:'Elio: hai dato un significato nuovo al nostro viaggio. Ci vediamo oltre la Lega.'});
 const l=make('league','Forte della Lega','sky','league',63);exit(l,13,16,'victory',13,2);obj(l,{kind:'league',x:13,y:4,name:'Custode della Lega'});obj(l,{kind:'center',x:6,y:10,name:'Infermiera',home:'league'});obj(l,{kind:'shop',x:20,y:10,name:'Emporio della Lega'});exit(l,24,9,'port',2,9,'champion');
 const port=make('port','Porto Imperiale','sky','town',66);exit(port,1,9,'league',23,9);exit(port,7,2,'lightIsland',13,14,'champion');exit(port,19,2,'shadowIsland',13,14,'light');exit(port,24,9,'kingdom',2,9,'both');sign(port,7,5,'Rotta occidentale','Isola delle Reliquie → Santuario della Luce');sign(port,19,5,'Rotta orientale','Isola dell’Ombra → Cripta di Noctivar');obj(port,{kind:'center',x:13,y:12,name:'Medico del porto',home:'port'});
 for(const [id,name,theme,boss,flag,lv] of [['light','Isola delle Reliquie','sky','Blanchivus','light',70],['shadow','Isola dell’Ombra','ghost','Noctivar','shadow',73]]){let a=make(id+'Island',name,theme,'route',lv-4);a.pool=id==='light'?['Terram','Ignivar','Elaris','Astrion','Dravurion']:['Noctelia','Morvik','Vargor','Armoryn'];exit(a,13,16,'port',id==='light'?7:19,3);exit(a,13,1,id+'Shrine');let sh=make(id+'Shrine',id==='light'?'Santuario della Luce':'Cripta di Noctivar',theme,'dungeon',lv);sh.pool=[];exit(sh,13,16,id+'Island',13,2);obj(sh,{kind:'legend',x:13,y:4,name:boss,flag,level:lv,text:id==='light'?'Blanchivus riconosce la Corona spezzata. Il patto vale più del dominio. Il guardiano vuole metterti alla prova.':'Noctivar custodisce il dolore cancellato dalle cronache. Affrontalo senza cancellare la sua memoria.'});}
 let k=make('kingdom','Regno Imperiale','grass','town',75);exit(k,1,9,'port',23,9);exit(k,13,1,'palace');sign(k,9,10,'Consigliera','Il regno si è riunito per scelta. La prova del Palazzo deciderà chi saprà custodire questo patto.');obj(k,{kind:'center',x:18,y:10,name:'Guaritore di corte',home:'kingdom'});let pal=make('palace','Palazzo Imperiale','dragon','gym',78);exit(pal,13,16,'kingdom',13,2);obj(pal,{kind:'emperor',x:13,y:4,name:'Maestra della Corona'});
 ['Lumeris','Marelune','Sylvaris','Aurex','Noctelia'].forEach((n,i)=>obj(maps['d'+i],{kind:'mythic',x:20,y:4,name:n,id:'mythic-'+n,level:68+i,required:'relic-'+i}));
 for(let i=0;i<8;i++){
 const m=maps['g'+i],labels=[['Radice','Foglia','Fiore'],['Indietro','Avanti','Gru carico/scarico'],['Disco I','Disco II','Disco III'],['Finestra I','Finestra II','Finestra III'],['Raffredda','Riscalda','Ponte'],['Lanterna I','Lanterna II','Lanterna III'],['Origine','Guerra','Promessa'],['Canale I','Canale II','Semina']][i];
 m.objects.filter(o=>o.kind==='switch').forEach(o=>{o.name=labels[o.index];if(i!==0&&i!==6)o.x=[6,13,20][o.index];});
 for(let x=1;x<25;x++)if(x!==13)m.grid[5][x]='wall';const sign=m.objects.find(o=>o.kind==='sign');sign.text=[
 'Tre tele chiudono la torre. Recidile seguendo il ciclo: Radice → Foglia → Fiore.',
 'La gru carica minerale alla stazione 1. Usa le leve per portare il carrello alla 4, quindi scarica: il peso aprirà il portale.',
 'Ruota i dischi astrali fino a ottenere 1 · 3 · 2. Ogni tocco avanza di un quarto di giro.',
 'Le correnti si bilanciano aprendo le finestre esterne e chiudendo quella centrale.',
 'La passerella resiste solo a calore 5. Usa raffreddamento e fuoco, poi aziona il ponte.',
 'Le lapidi rivelano la sequenza: Luce → Ombra → Luce. Accendi e spegni le tre lanterne.',
 'Ricomponi la storia: prima l’Origine del regno, poi la Guerra, infine la Promessa del guardiano.',
 'I canali hanno tre posizioni. Regola il primo a 2 e il secondo a 1, poi semina tre volte per far crescere tutte le aiuole.'
 ][i];
 }
 // Public gardens, fountains and inhabited archives give each settlement a readable layout.
 for(const m of Object.values(maps).filter(m=>m.kind==='town')){
  for(const o of m.objects)if(o.kind==='sign'&&!o.name.startsWith('Rotta'))o.kind='npc';
  obj(m,{kind:'fountain',x:10,y:7,name:'Fontana del patto'});
  for(const [x,y] of [[2,2],[3,2],[22,2],[23,2],[2,14],[3,14],[22,15],[23,15]])if(m.grid[y][x]==='grass')m.grid[y][x]='tree';
  for(let y=10;y<=14;y++)for(let x=3;x<=7;x++)if(!m.objects.some(o=>o.x===x&&o.y===y))m.grid[y][x]=m.theme==='grass'?'crop':'flower';
  if(m.id==='home'||/^c[0-7]$/.test(m.id)){
   const rid=m.id+'-archive';obj(m,{kind:'door',x:20,y:13,to:rid,tx:13,ty:14,name:m.id==='home'?'Laboratorio':'Archivio cittadino'});
   const archive=make(rid,m.id==='home'?'Laboratorio di Vannaccius':'Archivio · '+m.name,m.theme,'interior');exit(archive,13,16,m.id,20,14);
   obj(archive,{kind:'npc',x:13,y:5,name:m.id==='home'?'Professor Vannaccius':'Archivista',text:m.id==='home'?'Le creature crescono con l’esperienza condivisa. Se una sfida è difficile, cambia la composizione della squadra o esplora un santuario.':'Le cronache appartengono a tutti. Cerca il frammento della memoria nel santuario a est della città. Dopo la Lega i primi cinque santuari rivelano i loro custodi.'});
  }
 }
 return maps;}